# Generated by Django 6.0.5 on 2026-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject_letter",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Тема письма"),
                ),
                ("body_letter", models.CharField(blank=True, max_length=500, null=True, verbose_name="Тело письма")),
            ],
        ),
    ]
