# Generated by Django 6.0.5 on 2026-05-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("send_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=200, unique=True)),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                ("full_username", models.TextField(blank=True, null=True, verbose_name=" Ф.И.О.")),
                ("comment", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                ("server_response", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "Создана"), ("LAU", "Запущена"), ("COM", "Завершена")],
                        default="LAU",
                        max_length=3,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата начала расслыки"),
                ),
                (
                    "end_time",
                    models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата окончания рассылки"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="send_messages.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец рассылки",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="mailing.mailingrecipient", verbose_name="Получатели")),
            ],
        ),
    ]
