# Generated by Django 6.0.5 on 2026-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания рассылки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата начала расслыки"),
        ),
    ]
