# Generated by Django 6.0.5 on 2026-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_recipient"),
        ("mailing", "0002_alter_mailing_end_time_alter_mailing_start_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailingRecipient",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="client.recipient", verbose_name="Получатели"),
        ),
    ]
