# Generated by Django 6.0.5 on 2026-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_delete_mailingrecipient_alter_mailing_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("NEW", "Создана"), ("LAU", "Запущена"), ("COM", "Завершена")], default="NEW", max_length=3
            ),
        ),
    ]
