# Generated by Django 6.0.5 on 2026-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="full_username",
            field=models.TextField(blank=True, null=True, verbose_name=" Ф.И.О."),
        ),
    ]
