# Generated by Django 6.0.5 on 2026-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_comment_client_full_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="почта")),
                ("full_username", models.TextField(blank=True, null=True, verbose_name=" Ф.И.О.")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
