# Generated by Django 6.0.5 on 2026-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
        migrations.AddField(
            model_name="recipient",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
