# Generated by Django 6.0.5 on 2026-05-26 18:36
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_recipient_server_response_recipient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="attempt_time",
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
